# Usa una imagen base de Python ligera
FROM python:3.10-slim

# Establece un directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de tu proyecto al contenedor
COPY . /app

# Instala las dependencias especificadas en requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Comando para ejecutar tu proyecto
CMD ["python", "src/main.py"]